# Generated by Django 4.2.4 on 2023-08-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendorregister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=12)),
            ],
        ),
    ]
